// ==========================================================================
// 📖 课文与字词矩阵数据（按词组单位：全拼音与双语翻译无死角覆盖） - data.js
// ==========================================================================

const lessonTitle = "那是一堵墙";

const lessonData = [
    // --- 第1段 ---
    ["深冬的", "shēn dōng de", "of mid-winter", "musim sejuk yang dalam punya"],
    ["深夜，", "shēn yè", "late at night", "larut malam"],
    ["寒风", "hán fēng", "chilling wind / cold wind", "angin sejuk"],
    ["如刀子般", "rú dāo zi bān", "like a knife", "seperti pisau / bagai sembilu"],
    ["刮过", "guā guò", "blew across / swept through", "bertiup melepasi / melanda"],
    ["空旷的", "kōng kuàng de", "open and spacious / desolate", "yang lapang / sunyi"],
    ["清江", "qīng jiāng", "Qingjiang (river/place name)", "Qingjiang"],
    ["街道。", "jiē dào", "street", "jalan raya"],
    ["刚刚", "gāng gāng", "just now", "baru sahaja"],
    ["走出高墙的", "zǒu chū gāo qiáng de", "walked out of high walls (released from prison)", "melangkah keluar dari tembok tinggi (bebas penjara)"],
    ["青年", "qīng nián", "youth / young man", "pemuda"],
    ["小林，", "xiǎo lín", "Xiao Lin (name)", "Xiao Lin"],
    ["把破旧的", "bǎ pò jiù de", "take the shabby / worn-out", "baju yang usang / buruk (penanda objek)"],
    ["夹克衫", "jiá kè shān", "jacket", "jaket"],
    ["裹了又裹，", "guǒ le yòu guǒ", "wrapped tightly again and again", "membungkus rapat berkali-kali"],
    ["却", "què", "however / but", "namun / tetapi"],
    ["怎么也", "zěn me yě", "by no means / no matter how", "bagaimanapun pun"],
    ["挡不住", "dǎng bú zhù", "cannot block / keep out", "tidak dapat menahan / menghalang"],
    ["侵入", "qīn rù", "invade / penetrate", "menceroboh masuk / menusuk"],
    ["骨髓的", "gǔ suǐ de", "of bone marrow", "sumsum tulang punya"],
    ["冰冷。", "bīng lěng", "ice-cold / freezing", "kesejukan beku"],
    ["他已经", "tā yǐ jīng", "he already", "dia sudah"],
    ["三天", "sān tiān", "three days", "tiga hari"],
    ["没吃", "méi chī", "did not eat", "tidak makan"],
    ["一顿", "yí dùn", "a (classifier for meals)", "sehidangan / sekali"],
    ["饱饭了，", "bǎo fàn le", "full meal", "makan kenyang"],
    ["胃里", "wèi lǐ", "inside the stomach", "di dalam perut"],
    ["火烧火燎地", "huǒ shāo huǒ liǎo dì", "burning like fire / burning anxiety", "terasa panas membakar / pedih sangat"],
    ["疼。", "téng", "painful / aching", "sakit"],
    ["不远处，", "bù yuǎn chù", "not far away", "tidak jauh dari situ"],
    ["疏疏落落的", "shū shū luò luò de", "scattered / sparse", "yang jarang-jarang / bertaburan"],
    ["街角下，", "jiē jiǎo xià", "at the street corner", "di bawah penjuru jalan"],
    ["有一盏", "yǒu yì zhǎn", "there is a (classifier for lamps)", "ada sebuah"],
    ["昏黄的", "hūn huáng de", "dim yellow / dusk", "yang kuning suram / malap"],
    ["灯光", "dēng guāng", "lamp light", "cahaya lampu"],
    ["在寒风中", "zài hán fēng zhōng", "in the cold wind", "di dalam angin sejuk"],
    ["摇曳，", "yáo yè", "flickering / swaying", "berkelip-kelip / bergoyang"],
    ["那是一个", "nà shì yí gè", "that was a", "ia merupakan sebuah"],
    ["简陋的", "jiǎn lòu de", "simple and crude / shabby", "daif / usang / ringkas"],
    ["深夜面摊。", "shēn yè miàn tān", "late-night noodle stall", "gerai mi larut malam"],
    ["\n", "", "", ""],

    // --- 第2段 ---
    ["老板", "lǎo bǎn", "owner / boss", "tauke / bos"],
    ["是个", "shì gè", "is a", "merupakan seorang"],
    ["年迈的", "nián mài de", "elderly / aged", "yang tua uzur"],
    ["老头，", "lǎo tóu", "old man", "orang tua"],
    ["正", "zhèng", "right now", "sedang"],
    ["低着头", "dī zhe tóu", "lowering one's head", "menundukkan kepala"],
    ["在热气腾腾的", "zài rè qì téng téng de", "at the piping hot / steaming", "di dalam keadaan panas berasap"],
    ["锅前", "guō qián", "in front of the pot", "hadapan kuali / periuk"],
    ["忙碌。", "máng lù", "busy / bustling", "sibuk bekerja"],
    ["那锅里", "nà guō lǐ", "inside that pot", "di dalam periuk itu"],
    ["翻滚的", "fān gǔn de", "boiling / tumbling", "yang mendidih / bergelora"],
    ["白汤", "bái tāng", "white broth / white soup", "sup putih"],
    ["和", "hé", "and", "dan"],
    ["散发出的", "sàn fā chū de", "emitting / sending out", "yang mengeluarkan / memancarkan haruman"],
    ["暗香，", "àn xiāng", "subtle fragrance", "haruman yang lembut / wangi"],
    ["让小林", "ràng xiǎo lín", "made Xiao Lin", "membuatkan Xiao Lin"],
    ["咽了口", "yàn le kǒu", "swallowed a mouthful of", "menelan seteguk"],
    ["唾沫，", "tuò mo", "saliva / spit", "air liur"],
    ["内心的", "nèi xīn de", "inner heart's", "lubuk hatinya punya"],
    ["欲望", "yù wàng", "desire / urge", "keinginan / nafsu / hasrat"],
    ["像杂草一样", "xiàng zá cǎo yí yàng", "like weeds", "seperti rumput liar / rumpai"],
    ["疯狂", "fēng kuáng", "crazy / frantically", "gila-gilaan / mendadak"],
    ["滋生。", "zī shēng", "multiply / grow multiply", "membiak / tumbuh"],
    ["他摸了摸", "tā mō le mō", "he felt / patted", "dia meraba-raba"],
    ["空空如也的", "kōng kōng rú yě de", "absolutely empty", "yang kosong melongpo"],
    ["口袋，", "kǒu dài", "pocket", "poket / saku"],
    ["眼里", "yǎn lǐ", "in the eyes", "di dalam mata"],
    ["闪过一丝", "shǎn guò yì sī", "flashed a trace of", "terbayang seberkas / sekelip"],
    ["狠戾。", "hěn lì", "ruthlessness / ferocity", "kekejaman / kesadisan / niat jahat"],
    ["他打定", "tā dǎ dìng", "he made up mind", "dia menetapkan hati"],
    ["不到黄河心不死", "bú dào huáng hé xīn bù sǐ", "not stop until reaching the limit / completely determined", "tidak akan menyerah kalah selagi belum sampai ke penghujungnya"],
    ["的主意，", "de zhǔ yi", "idea / decision", "keputusan / tekad"],
    ["咬了咬牙，", "yǎo le yǎo yá", "grit one's teeth", "mengetap gigi / kuatkan semangat"],
    ["大步", "dà bù", "stride / big steps", "langkah besar"],
    ["走了过去。", "zǒu le guò qù", "walked over", "melangkah ke sana"],
    ["他", "tā", "he", "dia"],
    ["心想：", "xīn xiǎng", "thought to himself", "berfikir dalam hati:"],
    ["今晚", "jīn wǎn", "tonight", "malam ini"],
    ["横竖", "héng shù", "anyway / in any case", "apa-apa pun / walau bagaimanapun"],
    ["是个饱，", "shì gè bǎo", "is a full meal (to be full)", "tetap akan kenyang"],
    ["哪怕", "nǎ pà", "even if / no matter how", "walaupun / jika pun"],
    ["吃完", "chī wán", "after eating", "selesai makan"],
    ["被老头", "bèi lǎo tóu", "by the old man", "oleh orang tua itu"],
    ["当场揭穿、", "dāng chǎng jiē chuān", "exposed on the spot", "dibongkar di situ juga"],
    ["扭送进", "niǔ sòng jìn", "dragged and sent to / escort to", "ditangkap dan diserahkan ke"],
    ["派出所，", "pài chū suǒ", "police station", "balai polis"],
    ["也强过", "yě qiáng guò", "also better than", "adalah jauh lebih baik daripada"],
    ["在街头", "zài jiē tóu", "on the street", "di jalanan"],
    ["活活", "huó huó", "alive / while alive (starve to death)", "merana hidup-hidup"],
    ["冻死、", "dòng sǐ", "freeze to death", "mati kesejukan beku"],
    ["饿死！", "è sǐ", "starve to death", "mati kelaparan!"],
    ["\n", "", "", ""],

    // --- 第3段 ---
    ["“老板，", "lǎo bǎn", "Boss,", "Tauke,"],
    ["来一碗", "lái yì wǎn", "bring a bowl of", "minta semangkuk"],
    ["大份的", "dà fèn de", "large portion", "hidangan besar punya"],
    ["大排面！”", "dà pái miàn", "pork chop noodles", "mi sup daging hiris!"],
    ["小林", "xiǎo lín", "Xiao Lin", "Xiao Lin"],
    ["重重地", "zhòng zhòng dì", "heavily / forcefully", "dengan beratnya / menghempas diri"],
    ["坐下，", "zuò xià", "sat down", "duduk"],
    ["故意", "gù yì", "deliberately / on purpose", "sengaja"],
    ["把声音", "bǎ shēng yīn", "take the voice (object marker)", "suara (penanda objek)"],
    ["提得很大，", "tí de hěn dà", "raised very loud", "ditinggikan dengan kuat"],
    ["想要", "xiǎng yào", "wanting to", "mahu"],
    ["掩饰", "yǎn shì", "conceal / cover up / disguise", "menyembunyikan / menutup"],
    ["自己的", "zì jǐ de", "one's own", "sendiri punya"],
    ["嗫嚅与", "niè rú", "mumbling / hesitation", "keraguan dan"],
    ["怯懦。", "qiè nuò", "timidity / cowardice", "sifat penakut / segan"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["抬起", "tái qǐ", "raised up", "mengangkat"],
    ["凹陷下去的", "āo xiàn xià qù de", "sunken / hollowed", "yang cengkung / terperosok ke dalam"],
    ["眼睛", "yǎn jing", "eyes", "mata"],
    ["看了他", "kàn le tā", "looked at him", "memandangnya"],
    ["一眼，", "yì yǎn", "a glance", "sekilas"],
    ["那目光", "nà mù guāng", "that gaze / look", "pandangan mata itu"],
    ["出奇地", "chū qí dì", "surprisingly / unusually", "secara luar biasa / aneh sekali"],
    ["平静，", "píng jìng", "calm / peaceful", "tenang"],
    ["没有半点", "méi yǒu bàn diǎn", "without a single bit of", "tanpa sebarang / sedikit pun tidak ada"],
    ["迟疑。", "chí yí", "hesitation / delay", "ragu-ragu / teragak-agak"],
    ["很快，", "hěn kuài", "very quickly", "dengan cepat"],
    ["一碗", "yì wǎn", "a bowl of", "semangkuk"],
    ["热气腾腾、", "rè qì téng téng de", "piping hot / steaming", "panas berasap"],
    ["大排", "dài pái", "pork chop / steak hiris", "daging hiris"],
    ["厚得", "hòu de", "so thick that", "tebal sehinggakan"],
    ["像块金子", "xiàng kuài jīn zi", "like a piece of gold", "seperti sekeping emas"],
    ["的面", "miàn", "noodles", "punnya mi"],
    ["端了上来。", "duān le guò lái", "served up / brought over", "dihidangkan naik."],
    ["小林", "xiǎo lín", "Xiao Lin", "Xiao Lin"],
    ["等不得", "děng bù dé", "cannot wait", "tidak boleh tunggu"],
    ["半点", "bàn diǎn", "a single bit of / any", "sedikit pun"],
    ["停留，", "tíng liú", "stay / pause / delay", "berhenti"],
    ["狼吞虎咽地", "láng tūn hǔ yàn dì", "wolfing down / devouring", "makan dengan gelojoh / lahapnya"],
    ["往嘴里塞，", "wǎng zuǐ lǐ sāi", "stuffing into the mouth", "disumbat ke dalam mulut"],
    ["大口大口地", "dà kǒu dà kǒu dì", "in huge mouthfuls", "dengan suapan yang besar"],
    ["吞咽着。", "tūn yàn zhe", "swallowing", "sedang menelan."],
    ["这时候，", "zhè shí hou", "at this time", "pada waktu ini"],
    ["他眼角的", "tā yǎn jiǎo de", "his corner of the eyes", "dia punya ekor mata"],
    ["余光", "yú guāng", "peripheral vision / side glance", "pandangan sudut mata"],
    ["却", "què", "however", "namun"],
    ["始终", "shǐ zhōng", "from beginning to end / always", "sentiasa / dari awal hingga akhir"],
    ["贼一样地", "zé yí yàng dì", "like a thief", "seperti seorang pencuri"],
    ["死死盯着", "sǐ sǐ dīng zhe", "staring intently at", "merenung tajam pada"],
    ["老头的", "lǎo tóu de", "old man's", "orang tua itu punya"],
    ["每一个动作，", "měi gè dòng zuò", "every single movement", "setiap satu perbuatan"],
    ["多双眼睛，", "duō shuāng yǎn jing", "an extra pair of eyes", "sepasang mata lagi"],
    ["生怕", "shēng pà", "for fear that / deeply afraid", "bimbang kalau-kalau / takut sangat"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["看出", "kàn chū", "see through / notice", "melihat / mengesan"],
    ["他的", "tā de", "his", "dia punya"],
    ["异样", "yì yàng", "abnormality / strangeness", "keanehan / kelainan"],
    ["而", "ér", "and thus", "lalu"],
    ["提前报警。", "tí qián bào jǐng", "report to the police in advance", "melaporkan balai polis lebih awal."],
    ["\n", "", "", ""],

    // --- 第4段 ---
    ["好在", "hǎo zài", "fortunately / luckily", "mujur / nasib baik"],
    ["这一切，", "zhè yī qiè", "all of this", "semua ini"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["似乎", "sì hū", "seemingly / as if", "nampaknya / seolah-olah"],
    ["并没有", "bìng méi yǒu", "did not at all", "sememangnya tidak"],
    ["察觉。", "chá jué", "perceive / notice", "menyedari / perasan"],
    ["他", "tā", "he", "dia"],
    ["只是", "zhǐ shì", "only / just", "hanyalah"],
    ["静静地", "jìng jìng dì", "quietly", "dengan senyap / tenang"],
    ["坐在", "zuò zài", "sitting at", "duduk di"],
    ["炉子后面，", "lú zi hòu miàn", "behind the stove", "belakang dapur gas / relau"],
    ["任由", "rèn yóu", "allow / let", "membiarkan"],
    ["那锅里", "nà guō lǐ", "inside that pot", "di dalam periuk itu"],
    ["氤氲出来的", "yīn yūn chū lái de", "permeating out / steaming out", "yang menyelubungi keluar"],
    ["浓浓", "nóng nóng", "thick / dense", "yang pekat / tebal"],
    ["热气，", "rè qì", "hot steam / steam", "wap panas"],
    ["在两人", "zài liǎng rén", "between the two people", "di antara dua orang"],
    ["之间", "zhī jiān", "between / among", "antara"],
    ["隔开了", "gé kāi le", "separated / cut off", "memisahkan / menghalang"],
    ["一层", "yì céng", "a layer of", "lapisan"],
    ["厚厚的", "hòu hòu de", "thick", "yang tebal"],
    ["白雾。", "bái wù", "white mist / fog", "kabut putih / kabal putih"],
    ["那热气，", "nà rè qì", "that steam", "wap panas itu"],
    ["宛如", "wǎn rú", "just like / as if", "umpama / seolah-olah"],
    ["一堵", "yì dǔ", "a (classifier for walls)", "sebuah"],
    ["无形的", "wú xíng de", "invisible / intangible", "yang ghaib / tidak kelihatan"],
    ["墙，", "qiáng", "wall", "dinding / tembok"],
    ["把", "bǎ", "take (object marker)", "membawa (penanda objek)"],
    ["深夜的", "shēn yè de", "late night's", "larut malam punya"],
    ["寒冷", "hán lěng", "freezing cold / coldness", "kesejukan"],
    ["和", "hé", "and", "dan"],
    ["街头的", "jiē tóu de", "street's", "jalanan punya"],
    ["尘嚣", "chén xiāo", "hubbub / clamor of the world / dust", "hiruk-pikuk dunia / kekotoran"],
    ["通通", "tōng tōng", "all / completely", "kesemuanya sekali"],
    ["挡在了", "dǎng zài le", "blocked at", "menghalang di"],
    ["外面。", "wài miàn", "outside / exterior", "luar."],
    ["小林", "xiǎo lín", "Xiao Lin", "Xiao Lin"],
    ["吃得", "chī de", "ate until", "makan sehinggakan"],
    ["满头大汗，", "mǎn tóu dà hàn", "sweating profusely", "berpeluh-peluh satu kepala"],
    ["胃里", "wèi lǐ", "inside the stomach", "di dalam perut"],
    ["捂热了，", "wǔ rè le", "warmed up", "menghangatkan / memanaskan"],
    ["眼前的", "yǎn qián de", "in front of eyes", "di hadapan mata punya"],
    ["世界", "shì jiè", "world", "dunia"],
    ["也", "yě", "also", "pun"],
    ["仿佛", "fǎng fú", "as if / as though", "seakan-akan / seolah-olah"],
    ["亮堂了", "liàng táng le", "brightened up", "menjadi cerah"],
    ["起来。", "qià lái", "up", "semula."],
    ["当他", "dāng tā", "when he", "apabila dia"],
    ["吃下", "chī xià", "ate down", "memakan habis"],
    ["最后一口", "zuì hòu yì kǒu", "the very last mouthful", "suapan yang terakhir"],
    ["汤，", "tāng", "soup / broth", "sup"],
    ["擦了擦", "cā le cā", "wiped / cleaned", "mengelap-ngelap"],
    ["嘴，", "zuǐ", "mouth", "mulut"],
    ["正", "zhèng", "just right now", "sedang"],
    ["准备", "zhǔn bèi", "preparing to / planning to", "bersedia / berniat"],
    ["站起身", "zhàn qǐ shēn", "stand up", "bangun berdiri"],
    ["拔腿狂奔", "bá tuǐ kuáng bēn", "flee / take to one's heels running wildly", "membuka langkah seribu / memecut lari"],
    ["“吃白食”", "chī bái shí", "eating without paying / eating free food", "makan霸王餐 / makan tanpa bayar"],
    ["时，", "shí", "when", "apabila"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["却", "què", "however", "namun"],
    ["抢先一步", "qiǎng xiān yí bù", "forestall / take a step ahead", "melangkah selangkah lebih awal / mendahului"],
    ["走过来，", "zǒu guò lái", "walked over", "melangkah ke mari"],
    ["将一个", "jiāng yí gè", "take a (object marker)", "sebuah (penanda objek)"],
    ["沉甸甸的", "chén diàn diàn de", "heavy / heavy-laden", "yang berat / sarat"],
    ["塑料袋", "sù liào dài", "plastic bag", "beg plastik"],
    ["塞进", "sāi jìn", "stuffed into / rammed in", "menyumbat masuk into"],
    ["小林", "xiǎo lín", "Xiao Lin", "Xiao Lin punya"],
    ["手里。", "shǒu lǐ", "hand inside", "dalam tangan."],
    ["小林", "xiǎo lín", "Xiao Lin", "Xiao Lin"],
    ["惊得", "jīng de", "so shocked that", "terkejut sehinggakan"],
    ["魂飞魄散，", "hún fēi pò sàn", "frightened out of wits", "terperanjat besar / ketakutan"],
    ["所有的", "suǒ yǒu de", "all the", "kesemua"],
    ["防备", "fáng bèi", "defensiveness / precaution", "sikap berhati-hati / benteng diri"],
    ["与", "yǔ", "and", "dan"],
    ["绝望", "jué wàng", "despair / hopelessness", "kekecewaan / ketiadaan harapan"],
    ["重新", "chóng xīn", "anew / again", "sekali lagi / semula"],
    ["涌上心头。", "yǒng shàng xīn tóu", "welled up in the heart", "meluap ke hulu hati."],
    ["他以为", "tā yǐ wéi", "he thought / assumed", "dia menyangka bahawa"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["要动手了。", "yào dòng shǒu le", "was going to hit / act", "mahu bertindak / memukulnya."],
    ["谁知", "shéi zhī", "who would have thought / unexpectedly", "siapa sangka / tidak diduga"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["却", "què", "however", "namun / tetapi"],
    ["温和地", "wēn hé dì", "gently / mildly", "dengan lembut / mesra"],
    ["笑了笑，", "xiào le xiào", "smiled", "tersenyum sedikit"],
    ["轻轻地", "qīng qīng dì", "gently", "dengan perlahan / lembut"],
    ["拍了拍", "pāi le pāi", "patted", "menepuk-nepuk"],
    ["他的", "tā de", "his", "dia punya"],
    ["肩膀", "jiān bǎng", "shoulder", "bahu"],
    ["说：", "shuō", "said", "berkata:"],
    ["“年轻人，", "qīng nián rén", "young man", "orang muda / pemuda"],
    ["这袋子里", "zhè dài zi lǐ", "inside this bag", "di dalam beg ini"],
    ["有几块", "yǒu jǐ kuài", "there are several pieces of", "ada beberapa keping"],
    ["刚出锅的", "gāng chū guō de", "freshly cooked / fresh from the pot", "yang baru keluar dari periuk / kuali"],
    ["烧饼，", "shāo bǐng", "baked sesame cake / clay oven roll", "biskut bakar / roti bakar sesame"],
    ["你带在", "nǐ dài zài", "you take on", "kamu bawa di"],
    ["路上吃。", "lù shàng chī", "eat on the way", "perjalanan untuk makan."],
    ["今晚", "jiān wǎn", "tonight", "malam ini punya"],
    ["这面，", "zhè miàn", "this noodles", "mi ini"],
    ["算我", "suàn wǒ", "count as my", "dianggap sebagai saya punya"],
    ["请你的，", "qǐng nǐ de", "my treat to you", "belanja kamu punya"],
    ["不要钱。", "bú yào qián", "no money / free", "tidak usah bayar wang / percuma."],
    ["我年轻时，", "wǒ qīng nián shí", "when I was young", "semasa saya muda dahulu"],
    ["也", "yě", "also", "pun / juga"],
    ["走错坚固", "zǒu cuò le", "walked down the wrong (path)", "pernah tersalah melangkah jalan"],
    ["一段路，", "yí duàn lù", "a period of path / road", "sepanjang jalan / satu fasa"],
    ["知道", "zhī dào", "knowing that", "tahu bahawa"],
    ["人", "rén", "humans / people", "manusia"],
    ["在最冷的时候，", "zài zuì lěng de shí hou", "at the coldest time", "pada waktu yang paling sejuk"],
    ["心里", "xīn lǐ", "in the heart", "di dalam hati"],
    ["最缺的", "zuì quē de", "lacks the most", "paling kekurangan"],
    ["是一把火。", "shì yì bǎ huǒ", "is a fire", "adalah sebatang obor / api."],
    ["安心", "ān xīn", "with peace of mind", "dengan tenang hati"],
    ["往前走，", "wǎng qián zǒu", "walk forward", "melangkah ke hadapan"],
    ["别回头。”", "bié huí tóu", "don't look back", "jangan menoleh ke belakang."],
    ["\n", "", "", ""],

    // --- 第5段 ---
    ["听到", "tīng dào", "hearing", "mendengar"],
    ["这番", "zhè fān", "this speech / this kind of", "perbualan ini"],
    ["对话，", "duì huà", "dialogue / conversation", "perbualan / dialog"],
    ["小林的", "xiǎo lín de", "Xiao Lin's", "Xiao Lin punya"],
    ["心", "xīn", "heart", "jantung / hati"],
    ["就像", "jiù xiàng", "just like", "seolah-olah"],
    ["发生了", "fā shēng le", "occurred", "berlaku"],
    ["强烈的", "qiáng liè de", "intense / strong", "hebat / kuat"],
    ["地震", "dì zhèn", "earthquake", "gempa bumi"],
    ["一般，", "yī bān", "as if / like", "sedemikian"],
    ["久久", "jiǔ jiǔ", "for a long time", "lama sekali"],
    ["无法", "wú fǎ", "unable to / cannot", "tidak mampu / tidak boleh"],
    ["平静。", "píng jing", "calm down", "berasa tenang semula."],
    ["原来，", "yuán lái", "originally / turns out", "rupa-rupanya / asalnya"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu"],
    ["自始至终", "zì shǐ zhì zhōng", "from beginning to end / all along", "dari awal hingga akhir / semenjak awal lagi"],
    ["都看穿了", "dōu kàn chuān le", "all saw through", "kesemuanya sudah nampak jelas / faham"],
    ["他的", "tā de", "his", "dia punya"],
    ["窘迫", "jiǒng pò", "poverty / embarrassment / plight", "kesusahan hidup / kesempitan / kemaluan"],
    ["与", "yǔ", "and", "dan"],
    ["前科，", "qián kē", "criminal record / criminal past", "rekod jenayah lampau"],
    ["却用", "què yòng", "but using", "namun menggunakan"],
    ["这堵", "zhè dǔ", "this (wall)", "tembok... ini"],
    ["“热气的大墙”，", "rè qì de dà qiáng", "big wall of steam", "tembok besar wap panas"],
    ["默默地", "mò mò dì", "silently", "secara senyap / membisu"],
    ["将他的", "jiāng tā de", "take his (object marker)", "dia punya (penanda objek)"],
    ["狼狈", "láng bèi", "embarrassment / awkward plight", "keadaan kelam-kabut / aib"],
    ["与", "yǔ", "and", "dan"],
    ["难堪", "nán kān", "embarrassed / hard to bear", "kemaluan / kesusahan"],
    ["温柔地", "wēn róu dì", "gently / tenderly", "dengan penuh kelembutan"],
    ["包裹了", "bāo guǒ le", "wrapped up", "menyelubungi / membungkus"],
    ["起来，", "qǐ lái", "up", "semula"],
    ["没有让", "méi yǒu ràng", "did not let", "tidak membiarkan"],
    ["任何", "rèn hé", "any", "sebarang"],
    ["鄙夷", "bǐ yí", "disdain / contempt", "pandangan hina / jijik"],
    ["刺伤他。", "cì shāng tā", "hurt him / sting him", "melukainya."],
    ["看着", "kàn zhe", "looking at", "memandang"],
    ["手中", "shǒu zhōng", "in the hand", "di dalam tangan"],
    ["那袋", "nà dài", "that bag of", "sebungkus... itu"],
    ["捂热了", "wǔ rè le", "warmed up", "menghangatkan / memanaskan"],
    ["他冰冷双手的", "tā bīng lěng shuāng shǒu de", "his icy cold hands", "dia punya sepasang tangan yang sejuk beku"],
    ["烧饼，", "shāo bǐng", "baked sesame cakes", "roti bakar sesame"],
    ["再看着", "zài kàn kàn", "looking again at", "melihat sekali lagi ke arah"],
    ["老头", "lǎo tóu", "the old man", "orang tua itu punya"],
    ["那满足、", "mǎn zú", "satisfied", "kepuasan"],
    ["豁达的", "huò dá de", "open-minded / optimistic", "berlapang dada / fikiran terbuka"],
    ["笑容，", "xiào róng", "smile", "senyuman"],
    ["两行", "liǎng háng", "two lines", "dua titisan"],
    ["温热的泪水，", "wēn rè de lèi shuǐ", "warm tears", "air mata yang hangat"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["从这个", "cóng zhè gè", "from this", "daripada... ini"],
    ["曾经", "céng jīng", "once / ever", "pernah suatu masa"],
    ["铁石心肠的", "tiě shí xīn cháng de", "iron-hearted / stony-hearted", "berhati batu / keras kepala"],
    ["青年", "qīng nián", "youth / young man", "pemuda"],
    ["脸上", "liǎn shàng", "face", "wajah"],
    ["无声无息地", "wú shēng wú xī dì", "silently / without a sound", "tanpa sebarang bunyi"],
    ["淌下来。", "tǎng xià lái", "streamed down.", "mengalir turun."],
    ["树上有阳光，", "xīn zhōng yǒu yáng guāng", "having sunshine in heart (here: customized theme)", "ada cahaya matahari di dalam hati"],
    ["眼前", "yǎn qián", "in front of eyes", "di hadapan mata"],
    ["才会亮。", "cái huì liàng", "then will be bright", "baru akan cerah."],
    ["人心换人心，", "rén xīn huàn rén xīn", "mutual kindness exchanges hearts", "kebaikan dibalas kebaikan / hati tukar hati"],
    ["善良", "shàn liáng", "kindness / goodness", "kebaikan / ketulusan"],
    ["从来不是", "cóng lái bú shì", "has never been", "semenjak awal bukanlah"],
    ["高高在上的", "gāo gāo zài shàng de", "high and mighty / condescending", "berada tinggi di atas / angkuh / sombong"],
    ["施舍，", "shī shě", "alms / charity / donation", "sedekah / belas iksan"],
    ["而是在", "ér shì zài", "but rather at", "tetapi melainkan di dalam"],
    ["寒冷的", "hán lěng de", "freezing cold", "yang sejuk beku"],
    ["世界里，", "shì jiè lǐ", "world", "dunia"],
    ["用无声的", "wú shēng de", "silent", "dengan tanpa suara / senyap"],
    ["体面，", "tǐ miàn", "dignity / respectability / face", "maruah / harga diri / kehormatan"],
    ["为你", "wèi nǐ", "for you", "untuk kamu"],
    ["挡住", "dǎng zhù", "block / keep off", "menghalang / menepis"],
    ["风雨的", "fēng yǔ de", "wind and rain / hardships", "ribut dan hujan / kesukaran"],
    ["那一堵墙。", "nà yì dǔ qiáng", "that wall.", "sebuah dinding itu."],
    ["\n", "", "", ""],

    // --- 作者落款 ---
    ["（佚名《那是一堵墙》，有改动）", "", "", ""]
];
